### PR TITLE
Add environment variable expansion to values

### LINKED ISSUE #3: Variables not expanded in values
`.env` file:
```
FOO=test
BAR=$FOO
```

`.envrc` file:
```
dotenv
```

Command: `echo $BAR`
Expected output: `test`
Actual output: `$FOO`

### Links
- [Specs from ruby implementation](https://github.com/bkeepers/dotenv/blob/master/spec/dotenv/parser_spec.rb#L49-L56)

### PR DESCRIPTION
**Pull request by hakamadare**
This uses `os.ExpandEnv()`, so it expands environment variables, but
does not provide any other shell-specific expansions (_e.g._ command
substitution).

Resolves #3

### CODE REVIEW

**Comment by zimbatm** [comment]
What is supposed to happen if the referenced env is from a previous line? Eg:
```
export FOO=abc
export BAR=${FOO}def
```

**Comment by hakamadare** [comment]
@zimbatm that will not produce anything useful; that's why this is a first pass at the implementation :)  i can think of two ways to enable self-referential variable expansion, and i'm not sure i like either of them:

1. pass a pointer to the `dotenv` map into `parseValue()`, so that while a line is being parsed, i can look up variables that are already keys in `dotenv`
2. call `os.Setenv(key, value)` from within each call of `parseValue()`, which would stuff the variables into the environment as they are parsed, but that seems like an ugly side effect and could make it more difficult to clean up the variables later on

**Comment by hakamadare** [comment]
actually!   i just thought of a failure case we'd like to avoid.  since `os.ExpandEnv()` doesn't support escaping metacharacters, i've modified my PR such that it doesn't clobber strings that do not map to environment variables.

so in your example above, the environment variable `BAR` would be set to the literal string `${FOO}dev`.  that seems not the most useful, but it is safe (_i.e._ it will not produce unpleasant surprises for people who depend on the current behavior of the library).

**Comment by zimbatm** [comment]
According to https://github.com/bkeepers/dotenv#variable-substitution the user should single-quote the value to prevent substitution. The format doesn't have a spec so you should look at https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/substitutions/variable.rb for the canonical implementation.

**Comment by hakamadare** [comment]
@zimbatm Got it.  My latest commit, I believe, complies with that spec; how does that look to you?  I've removed the feature of preserving unset variables; now if someone writes `$FOO` in their .env and FOO is unset, the library will expand that to the empty string, unless the entire value is enclosed in single quotes.

I'm not opposed to also trying to work on shell command expansion, but that's a bit trickier, so I'd prefer to do it in a separate PR.

**Comment by zimbatm** [comment]
Nice, it looks much better. I agree that command expansion could be implemented separately. I think that it's a bit of a mis-feature as it makes `.env` impure and potentially dangerous to load.

The only remaining thing to do is to have expandEnv look in the map of new environments:

```
$ cat .env
export FOO=bar
export BAR=${FOO}

$ irb
irb(main):001:0> require "dotenv"
=> true
irb(main):002:0> Dotenv.load
=> {"FOO"=>"bar", "BAR"=>"bar"}
irb(main):003:0> 
```

**Comment by hakamadare** [comment]
@zimbatm done; i now pass around a pointer to `dotenv` and mutate it inside of `parseValue()`, which makes it easier to look up values while expanding.

at this point i finally think i've got it; if you see something i've missed, lmk, and i'll add another test for that case :) thanks for your patience as i work through this; i have the specific use case of wanting to expand `$PWD` inside a dotenv file, but i suspect that building a reasonably standards-compliant implementation will help other people as well.

**Review by zimbatm — APPROVED** [review]
nice!

**Comment by zimbatm** [comment]
https://github.com/direnv/direnv/pull/433

**Pull request merged**
